---

- name: Disable default MariaDB module
  ansible.builtin.command: dnf -y module disable mariadb

- name: Ensure PyMySQL is installed (RHEL/CentOS/Fedora)
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: present
  when: ansible_os_family == "RedHat"

- name: Add MariaDB official repo for 11.4
  ansible.builtin.shell: >
    curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup
    | sudo bash -s -- --mariadb-server-version="mariadb-11.4"
  args:
    executable: /bin/bash
  register: mariadb_repo
  changed_when: "'Repo added' in mariadb_repo.stdout"

- name: Install latest MariaDB server from official repo
  ansible.builtin.yum:
    name:
      - MariaDB-server
      - MariaDB-client
      - MariaDB-common
      - MariaDB-shared
      - MariaDB-backup
    state: latest


- name: Start and enable MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- import_tasks: secure.yml

- name: Configure MariaDB master
  ansible.builtin.template:
    src: master.cnf.j2
    dest: /etc/my.cnf.d/master.cnf
  notify: Restart MariaDB


- name: Ensure MaxScale monitor user exists on master and for replication
  community.mysql.mysql_user:
    name: repl
    host: '%'
    password: "{{ mariadb_repl_password }}"
    priv: >
      *.*:REPLICATION SLAVE,REPLICATION CLIENT,BINLOG MONITOR,SUPER,SLAVE MONITOR,PROCESS,RELOAD/mysql.*:SELECT
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Ensure MaxScale monitor user exists on master and for maxscale work
  community.mysql.mysql_user:
    name: maxscaleuser
    host: '%'
    password: maxscalepassword
    priv: >
      *.*:REPLICATION SLAVE,REPLICATION CLIENT,BINLOG ADMIN,SUPER,SLAVE MONITOR,REPLICATION SLAVE ADMIN,REPLICATION MASTER ADMIN,PROCESS,RELOAD,READ_ONLY ADMIN,SHOW DATABASES/mysql.*:SELECT
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

